var rule = {
  title: '如意影院',
  host: 'https://www.51chedi.com/',
  url: '/ruyisw/fyclass--------fypage---.html',
  searchUrl: '/ruyisc/**----------fypage---.html',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  class_parse: '.myui-header__menu li.hidden-sm;a&&Text;a&&href;/(\\d+).html',
  play_parse: true,
  lazy:muban.mx.lazy,
  limit: 6,
  double: true,
  推荐: 'ul.myui-vodlist.clearfix;li;a&&title;a&&data-original;.pic-text&&Text;a&&href',
  一级: '.myui-vodlist li;a&&title;a&&data-original;.pic-text&&Text;a&&href',
  二级: {
    title: '.myui-content__detail .title--span&&Text;.myui-content__detail p.data:eq(0)&&Text',
    img: '.myui-content__thumb .lazyload&&data-original',
    desc: '.myui-content__detail p:eq(2)&&.text-red&&Text;.data a:eq(2)&&Text;.data a:eq(1)&&Text;.myui-content__detail p.data:eq(2)&&Text;.myui-content__detail p.data:eq(3)&&Text',
    content: '.myui-content__detail p:eq(5)&&Text',
    tabs: '.nav.nav-tabs.active&&li',
    lists: '.myui-content__list:eq(#id) li',
  },
  cate_exclude: "电影|电视剧|综艺|动漫",
  搜索: '#searchList li;a&&title;.lazyload&&data-original;.pic-text&&Text;a&&href;.detail&&Text',
}